#########################################################################################
# REQUÊTES ENVOYEES AU SERVEUR "config-test"
#########################################################################################


#########################################################################################
# (01.)INTERROGER LE "config-server" PAR DEFAUT
#########################################################################################
GET http://localhost:9101/default

#########################################################################################
# (02.)CONSULTER LES PROPRIETES DU "micro-service-produit"
#########################################################################################
GET http://localhost:9101/microservice-produit/default
