#########################################################################################
# REQUÊTES ENVOYEES AU SERVEUR "UtilisateurServer"
#########################################################################################


#########################################################################################
# (01.)INTERROGER LE "UtilisateurServer" PAR DEFAUT
#########################################################################################
GET http://localhost:9010/default

#########################################################################################
# (02.)ACTUALISER LES PROPRIETES DU "UtilisateurServer"
#########################################################################################
POST http://localhost:9010/actuator/refresh

#########################################################################################
# (03.)CONSULTER LA LISTE DES UTILISATEURS
#########################################################################################
GET http://localhost:9010/utilisateur
