######################################################
# ---- (01.)LOGGING-CONFIGURATION ----
######################################################
logging:
  config: "classpath:log4j2-spring.xml"

######################################################
# ---- (02.)SERVER-PORT-CONFIGURATION ----
######################################################
server:
  port: 9010

######################################################
# ---- (03.)ACTUATOR-CONFIGURATION ----
######################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"

######################################################
# ---- (04.)EUREKA-CONFIGURATION ----
######################################################
#eureka:
  #client:
    #serviceUrl:
      #defaultZone: "http://localhost:9102/eureka/"

######################################################
# ---- (05.)SPRING-CONFIGURATION ----
######################################################
spring:
  # ---- (05.01.)SPRING-APPLICATION-CONFIGURATION ----
  application:
    name: "utilisateurServer"
  # ---- (05.02.)SPRING-DATASOURCE-CONFIGURATION ----
  datasource:
    url: "jdbc:mariadb://localhost:3306/utilisateurdb?createDatabaseIfNotExist=true"
    username: "root"
    password: "toor"
    driver-class-name: "org.mariadb.jdbc.Driver"
    sql-script-encoding: UTF-8
    data: "classpath:import.sql"
    #initialization-mode: always
    #initialize: true
  # ---- (05.03.)SPRING-JPA-CONFIGURATION ----
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MariaDBDialect"
  # ---- (05.04.)SPRING-SECURITY-CONFIGURATION ----
  #security:
    #user:
      #name: "utilisateur"
      #password: "mdp"

######################################################
# ---- (06.)SECURITY-CONFIGURATION ----
######################################################
#security:
  #oauth2:
    #resource:
      #loadBalanced: true
      #userInfoUri: "http://localhost:9104/user"
