#########################################################################################
# REQUÊTES ENVOYEES AU SERVEUR "microservice-produit"
#########################################################################################


#########################################################################################
# (01.)INTERROGER LE "microservice-produit" PAR DEFAUT
#########################################################################################
GET http://localhost:9010/default

#########################################################################################
# (02.)ACTUALISER LES PROPRIETES DU "microservice-produit"
#########################################################################################
POST http://localhost:9010/actuator/refresh

#########################################################################################
# (03.)CONSULTER LA LISTE DES PRODUITS
#########################################################################################
GET http://localhost:9010/produit
